services:

  cache:
    build:
      context: ./
      dockerfile: ./docker/cache/Dockerfile
    container_name: entropy_cache
    env_file:
      - ./docker/cache/.env
    image: entropy_cache
    ports:
      - 6379:6379
    volumes:
      - ./data/cache:/data
    networks:
      - entropy

  core-backend:
    build:
      context: ./
      dockerfile: ./docker/core-backend/Dockerfile
    container_name: entropy_core_backend
    env_file:
      - ./docker/core-backend/.env
    image: entropy_core_backend
    ports:
      - 8000:8000
      - 443:443
    volumes:
      - ./src/core-backend:/entropy
      - ./logs/core-backend:/root/.symfony5/log
    networks:
      - entropy

  database:
    build:
      context: ./
      dockerfile: ./docker/database/Dockerfile
    container_name: entropy_database
    env_file:
      - ./docker/database/.env
    image: entropy_database
    ports:
      - 3306:3306
    volumes:
      - ./data/database:/var/lib/mysql
    networks:
      - entropy

  database-viewer:
    container_name: entropy_database_viewer
    build:
      context: ./
      dockerfile: ./docker/database-viewer/Dockerfile
    image: entropy_database_viewer
    ports:
      - 8080:80
    env_file:
      - ./docker/database-viewer/.env

  notification-backend:
    container_name: entropy_notification_backend
    build:
      context: ./
      dockerfile: ./docker/notification-backend/Dockerfile
    image: entropy_notification_backend
    ports:
      - 3000:3000
    volumes:
      - ./src/notification-backend:/entropy
    env_file:
      - ./docker/notification-backend/.env

networks:
  entropy:
    name: entropy
